-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprland/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.env")
-- Source: ~/.config/hypr/hyprland/execs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.execs")
-- Source: ~/.config/hypr/hyprland/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.general")
-- Per-monitor workspace blocks (1-10 built-in, 11-20 first external, ...).
require("hyprland.workspaces")
-- Source: ~/.config/hypr/hyprland/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.rules")
-- Source: ~/.config/hypr/hyprland/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.colors")
-- Source: ~/.config/hypr/hyprland/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.keybinds")
