-- exec = export SLURP_ARGS='-d -c DDE1FFBB -b 3F456544 -s 00000000'

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        col = {
            active_border = "rgba(DEE2EF39)",
            inactive_border = "rgba(8B919F30)",
        },
    },
    misc = {
        background_color = "rgba(0F131CFF)",
    },
})

if hl.plugin.hyprbars then
    hl.config({
        plugin = {
            hyprbars = {
                bar_text_font = "Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif",
                bar_height = 30,
                bar_padding = 10,
                bar_button_padding = 5,
                bar_precedence_over_border = true,
                bar_part_of_window = true,
                bar_color = "rgba(0F131CFF)",
                col = { text = "rgba(DEE2EFFF)" },
            },
        },
    })

    local button_color = "rgb(DEE2EF)"
    hl.plugin.hyprbars.add_button({ bg_color = button_color, fg_color = button_color, size = 13, icon = "󰆭", action = [[hyprctl dispatch 'hl.dsp.window.close()']] })
    hl.plugin.hyprbars.add_button({ bg_color = button_color, fg_color = button_color, size = 13, icon = "󰆯", action = [[hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" })']] })
    hl.plugin.hyprbars.add_button({ bg_color = button_color, fg_color = button_color, size = 13, icon = "󰆰", action = [[hyprctl dispatch 'hl.dsp.window.move({ workspace = "special", follow = false })']] })
end

hl.window_rule({
    match = { pin = true },
    border_color = "rgba(A9C7FFAA) rgba(A9C7FF77)",
})
