-- Bar, wallpaper
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Core components (authentication, lock screen, notification daemon)

-- Clipboard: history
--exec-once = wl-paste --type text --watch cliphist store
--exec-once = wl-paste --type image --watch cliphist store

-- Cursor
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")

-- KDE connect

-- Plugins
-- exec-once = hyprpm reload

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/scripts/color_generation/start-wallpaper-daemon.sh")
    hl.exec_cmd("/usr/lib/geoclue-2.0/demos/agent & gammastep")
    hl.exec_cmd("quickshell &")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("hyprpm reload && hyprctl reload")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("/usr/local/bin/clipsync watch without-notifications")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("~/.config/ags/scripts/hyprland/fix_portals.sh")
    hl.exec_cmd("kdeconnect-indicator &")
end)

-- The wallpaper daemon caches per output name, so a monitor it has never
-- seen comes up blank until the current wallpaper is pushed to it.
hl.on("monitor.added", function()
    hl.exec_cmd("~/.config/hypr/scripts/color_generation/wallpaper-fill-outputs.sh")
end)
