--####### Window rules ########
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        title = ".*",
    },
    no_blur = true,
    opacity = "0.95 override",
})

-- windowrule = float, match:class ^(blueberry.py)$
-- windowrule = float, match:class ^(steam)$
-- windowrule = float, match:class ^(guifetch)$  # FlafyDev/guifetch

-- Warp
hl.window_rule({
    match = {
        class = "dev.warp.Warp",
    },
    float = false,
})

-- Picture-in-Picture
hl.window_rule({
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    float = true,
})

-- Center common dialogs
hl.window_rule({
    match = {
        title = "^(Open File)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Select a File)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Open Folder)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Save As)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Library)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(File Upload)(.*)$",
    },
    center = true,
})

-- windowrule = no_initial_focus, match:title .*

-- Dialogs (floating)
hl.window_rule({
    match = {
        title = "^(Open File)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Select a File)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open Folder)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Save As)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Library)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(File Upload)(.*)$",
    },
    float = true,
})

-- Tearing
hl.window_rule({
    match = {
        title = ".*\\.exe",
    },
    immediate = true,
})

hl.window_rule({
    match = {
        class = "^steam_app_.*$",
    },
    immediate = true,
    opacity = "1 override",
})

-- No shadow for tiled windows
hl.window_rule({
    match = {
        float = 0,
    },
    no_shadow = true,
})

--####### Layer rules ########
hl.layer_rule({
    match = { namespace = ".*" },
    xray = true,
})

-- layerrule = no_anim, match:namespace .*   # Example: disable all layer animations

hl.layer_rule({
    match = { namespace = "walker" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "selection" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "overview" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "anyrun" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "indicator.*" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "osk" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "hyprpicker" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "shell:.*" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "noanim" },
    no_anim = true,
})

hl.layer_rule({
    match = { namespace = "gtk-layer-shell" },
    blur = true,
    ignore_alpha = 0,
})

hl.layer_rule({
    match = { namespace = "launcher" },
    blur = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = { namespace = "notifications" },
    blur = true,
    ignore_alpha = 0.69,
})

hl.layer_rule({
    match = { namespace = "mako" },
    blur = true,
    ignore_alpha = 0.69,
})

-- ags / bars / docks etc.
hl.layer_rule({
    match = { namespace = "sideleft.*" },
    animation = "slide top",
})

hl.layer_rule({
    match = { namespace = "sideright.*" },
    animation = "slide top",
})

hl.layer_rule({
    match = { namespace = "session" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "bar" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "corner.*" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "dock" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "indicator.*" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "overview" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "cheatsheet" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "sideright" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "sideleft" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "indicator*" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "osk" },
    blur = true,
    ignore_alpha = 0.6,
})

--######## USER rules ########
-- Spotify
hl.window_rule({
    match = {
        class = "spotify",
    },
    no_initial_focus = true,
    workspace = "10",
})

-- Feishin
hl.window_rule({
    match = {
        class = "feishin",
    },
    no_initial_focus = true,
    workspace = "10",
})

-- Packet Tracer
hl.window_rule({
    match = {
        class = "PacketTracer",
    },
    no_initial_focus = true,
})

-- DBeaver
hl.window_rule({
    match = {
        class = "DBeaver",
    },
    no_initial_focus = true,
})

-- Beat Saber Oneclick helper
hl.window_rule({
    match = {
        class = "bs-oneclick.py",
    },
    float = true,
    size = { 180, 100 },
})

-- FreeCAD
hl.window_rule({
    match = {
        class = "FreeCAD",
    },
    no_initial_focus = true,
    suppress_event = "activatefocus",
})

-- Gromit screen annotation overlay
hl.window_rule({
    match = {
        class = "gromit-mpx",
    },
    workspace = "special:gromit",
})

hl.window_rule({
    match = {
        class = "Gromit-mpx",
    },
    workspace = "special:gromit",
})

hl.window_rule({
    match = {
        class = "gromit-mpx",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "Gromit-mpx",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "gromit-mpx",
    },
    stay_focused = true,
})

hl.window_rule({
    match = {
        class = "Gromit-mpx",
    },
    stay_focused = true,
})

hl.window_rule({
    match = {
        class = "gromit-mpx",
    },
    no_anim = true,
})

hl.window_rule({
    match = {
        class = "Gromit-mpx",
    },
    no_anim = true,
})

-- Android Studio
hl.window_rule({
    match = {
        class = "jetbrains-studio",
    },
    no_initial_focus = true,
})

-- KDE Connect
hl.window_rule({
    match = {
        class = "org.kde.kdeconnect.daemon",
    },
    no_initial_focus = true,
    workspace = "11",
})

-- KiCad
hl.window_rule({
    match = {
        title = ".*— KiCad.*",
    },
    workspace = "6",
})

hl.window_rule({
    match = {
        title = ".*Schematic Editor$",
    },
    workspace = "7",
})

hl.window_rule({
    match = {
        title = ".*PCB Editor$",
    },
    workspace = "8",
})

hl.window_rule({
    match = {
        class = "KiCad",
        title = "3D Viewer$",
    },
    float = true,
    workspace = "8",
})

-- windowrule = size 10% 100%, match:title kicad\-wakatime.*
hl.window_rule({
    match = {
        class = "kicad",
    },
    size = "1280 1000",
})

-- STM32CubeIDE
hl.window_rule({
    match = {
        class = "org-eclipse-core-internal-jobs-Worker",
    },
    stay_focused = true,
})

-- GIMP
hl.window_rule({
    match = {
        class = "gimp",
    },
    opacity = 1,
    no_initial_focus = true,
    suppress_event = "activatefocus",
})

hl.window_rule({
    match = {
        tag = "opaque_toggle",
    },
    opaque = true,
    opacity = "1 override",
})

-- Waydroid
hl.window_rule({
    match = {
        class = "Waydroid",
    },
    float = false,
    pseudo = true,
    center = true,
})
